sudo: required
language: generic

services:
  - docker

script:
  - docker build -t kacperkwiatkowski/nginx-tweet ./nginx
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kacperkwiatkowski/nginx-tweet

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: tweet-app-complete
  env: Tweetappcomplete-env
  bucket_name: elasticbeanstalk-eu-central-1-195077249767
  bucket_path: tweet-app-bucket
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY