sudo: required
language: generic

services:
  - docker

script:
  - docker build -t kacperkwiatkowski/nginx-tweet ./nginx
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kacperkwiatkowski/nginx-tweet