version: '3.9'

services:
  backend-tweet-prod:
    image: kacperkwiatkowski/backend-tweet
    container_name:   backend-tweet-prod
    environment:
      DB_USERNAME: mongousername
      DB_PASSWORD: mongopassword
      DB_NAME: mongo-tweets
      DB_HOST: mongo-tweets-prod
      DB_PORT: 27017
    hostname: backend-tweet-prod
    ports:
      - "8080:8080"
    depends_on:
      - mongo-tweets-prod
    networks:
      - nginx-network

  frontend-tweet-prod:
    image: kacperkwiatkowski/frontend-tweet
    container_name: frontend-tweet-prod
    hostname: frontend-tweet-prod
    networks:
      - nginx-network

  nginx-tweet-prod:
    image: kacperkwiatkowski/nginx-tweet
    container_name: nginx-tweet-prod
    hostname: nginx-tweet-prod
    ports:
      - "80:80"
    depends_on:
      - backend-tweet-prod
      - frontend-tweet-prod
    networks:
      - nginx-network

  mongo-tweets-prod:
    image: mongo
    container_name: mongo-tweets-prod
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongousername
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge