version: '3.9'

services:
  backend-tweet-prod:
    image: kacperkwiatkowski/backend-tweet
    container_name: backend-tweet-prod
    environment:
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
    hostname: backend-tweet-prod
    ports:
      - "8080:8080"
    networks:
      - nginx-network
    env_file:
      - .env

  frontend-tweet-prod:
    image: kacperkwiatkowski/frontend-tweet
    container_name: frontend-tweet-prod
    networks:
      - nginx-network

  nginx-tweet-prod:
    container_name: nginx-tweet-prod
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - backend-tweet-prod
      - frontend-tweet-prod
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge

