version: '3.9'

services:
  backend-tweet-prod:
    image: kacperkwiatkowski/backend-tweet
    container_name: backend-tweet-prod
    environment:
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
    hostname: backend-tweet-prod
    ports:
      - "8080:8080"
    depends_on:
      - mongo-tweets-prod
    networks:
      - nginx-network

  frontend-tweet-prod:
    image: kacperkwiatkowski/frontend-tweet
    container_name: frontend-tweet-prod
    hostname: frontend-tweet-prod
    networks:
      - nginx-network

  nginx-tweet-prod:
    image: kacperkwiatkowski/nginx-tweet
    container_name: nginx-tweet-prod
    hostname: nginx-tweet-prod
    ports:
      - "80:80"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge