version: '3.9'

services:
  backend-tweet:
    image: kacperkwiatkowski/backend-tweet
    container_name: backend-tweet
    environment:
      DB_USERNAME: mongousername
      DB_PASSWORD: mongopassword
      DB_NAME: mongo-tweets
      DB_HOST: mongo-tweets
      DB_PORT: 27017
    depends_on:
      - mongo-tweets


  frontend-tweet:
    image: kacperkwiatkowski/frontend-tweet
    container_name: frontend-tweet

  nginx-tweet:
    build:
      dockerfile: ./nginx/Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - backend-tweet
      - frontend-tweet

  mongo-tweets:
    image: mongo
    container_name: mongo-tweets
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongousername
      MONGO_INITDB_ROOT_PASSWORD: mongopassword