version: '3.9'

services:
  backend-tweet-prod:
    image: kacperkwiatkowski/backend-tweet
    container_name: backend-tweet-prod
    environment:
      MAIL_USERNAME: kacper.kwiatkowski.cognizant@gmail.com
      MAIL_PASSWORD: rjjlkwyzdsnxktyz
      AWS_ACCESS_KEY: AKIAS224CTLTXQ5SKKXQ
      AWS_SECRET_KEY: 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
    hostname: backend-tweet-prod
    ports:
      - "8080:8080"
    networks:
      - nginx-network

  frontend-tweet-prod:
    image: kacperkwiatkowski/frontend-tweet
    container_name: frontend-tweet-prod
    hostname: frontend-tweet-prod
    networks:
      - nginx-network

  nginx-tweet-prod:
    image: kacperkwiatkowski/nginx-tweet
    container_name: nginx-tweet-prod
    hostname: nginx-tweet-prod
    ports:
      - "80:80"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge